version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_started
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery_worker:
    build: .
    command: celery -A app.main.celery_app worker --loglevel=info
    environment:
      MONGO_URI: mongodb://mongo:27017
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_started
    volumes:
      - .:/app

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: